# Generated by Django 5.2.1 on 2025-06-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_info_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Info'},
        ),
        migrations.RemoveField(
            model_name='info',
            name='message',
        ),
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
    ]
